### PR TITLE
Realign from cram version reference

### PR DESCRIPTION
**Pull request by illusional**
Needs commentary for how to portably specify the references.
I've added a fix to the named-pipes implementation around sorting the crams, eg: https://batch.hail.populationgenomics.org.au/batches/97703

### CODE REVIEW

**Comment by illusional** [comment]
Hey @vladsavelyev, what's the best way to portably specify the references from previous version? I fear the current implementation is not portable with the goals of this project?

**Comment by vladsavelyev** [comment]
I'd configure the realignment reference path in the config. Longer term, we probably want to pull it from metamist?

**Comment by vladsavelyev** [comment]
MarkDup and HaplotypeCaller work perfectly now for all seqr samples. As well as re-aligning from CRAMs. Thanks a lot for help optimising! I'll merge this branch if that's okay? @illusional

**Review by vladsavelyev — APPROVED** [review]

**Comment by illusional** [comment]
Perfect, thanks for texting @vladsavelyev!!

**Pull request merged**
