### PR TITLE
Rare disease RNA pipeline - Outrider

### PR DESCRIPTION
**Pull request by mgeaghan**
This stage performs aberrant gene expression detection for rare disease cohorts using the R package Outrider. The stage takes as input the `<SAMPLE_ID>.count` file generated by the count stage and runs an R script to perform the analysis.

The R script is coded as a docstring in the hail batch command, i.e.

```bash
R --vanilla <<EOF
library(OUTRIDER)
# R code ...
EOF
```

The stage produces a number of outputs for the entire cohort:

- COHORT_ID.outrider.RData - an RData object containing key objects from the analysis pipeline
- COHORT_ID.outrider.results.txt - significant aberrant gene expression results
- COHORT_ID.outrider.results.all.txt - all aberrant gene expression results, including non-sigificant ones
- COHORT_ID.outrider.aberrant_genes_per_sample.txt - summary of the number of aberrant genes per sample
- COHORT_ID.outrider.aberrant_samples_per_gene.txt - summary of the number of individuals with aberrant gene expression per gene
- COHORT_ID.outrider.gene_plots.tar.gz - QQ plots, expression-rank plots, and expected vs observed counts per gene
- COHORT_ID.outrider.heatmaps.tar.gz - correlation heatmaps
- COHORT_ID.outrider.stats_plots.tar.gz - miscellaneous statistics plots
- COHORT_ID.outrider.volcano_plots.tar.gz - volcano plots for each sample with significant results

### CODE REVIEW

**Comment by MattWellie** [comment]
@mgeaghan GitHub is being a bit funny - It looks like this has been open a while so it's not correctly assessing the difference between this branch and Main (comparison [here](https://github.com/populationgenomics/production-pipelines/compare/main...outrider) is 431 lines, this PR is 1750).

Could you please close this and re-open as a new PR (same description etc.)

**Comment by MattWellie** [comment]
> GitHub is being a bit funny - It looks like this has been open a while so it's not correctly assessing the difference between this branch and Main (comparison [here](https://github.com/populationgenomics/production-pipelines/compare/main...outrider) is 431 lines, this PR is 1750).

Looks like this has resolved itself, please ignore that comment :)

**Comment by mgeaghan** [comment]
I've merged the latest changes from main and updated the code to point to the correct parameters for grabbing the GTF. Tested successfully.

**Review by MattWellie — APPROVED** [review]
LGTM

**Pull request merged**
