### PR TITLE
Ensure populated CramPaths have both path and index_path

### PR DESCRIPTION
**Pull request by jmarshall**
Followup to PR #537: We need `sequencing_group.cram` to be a CramPath as established by the previous PR, but we also need to ensure that `sequencing_group.cram.index_path` is also set (where applicable?), which requires a suitable value to be provided to the constructor call.

There are surely better ways to query or construct this value. Is it available perhaps via the same metamist call? Is it always available, or do we need to do an `.exists()` and leave this as None if not?

### CODE REVIEW

**Comment by jmarshall** [comment]
I haven't tested by hand that the `with_suffix` extension used and utils's `exists()` method do the right thing for us. However `.with_suffix('.cram.crai')` is what is already used elsewhere for these files, and the tests should exercise all this code anyway too.

**Comment by jmarshall** [comment]
I assume there's nothing you need to set up first to use the caching `exists(…)` function…?

**Comment by illusional** [comment]
@jmarshall, nothing needed, just throw the path at it and it should do the rest (the power of decorators)

**Review by MattWellie — APPROVED** [review]
I like this change. Can we chuck a version bump in

**Pull request merged**
