### PR TITLE
Add dataset path to predetermined_qc_variants

### PR DESCRIPTION
**Pull request by KatalinaBobowik**
Make the `predetermined_qc_variants` sites table automatically pull from the relevant bucket using the `dataset_path` function. 

For context, see the conversation in Slack [here](https://centrepopgen.slack.com/archives/C03FA2M1MR9/p1700203648189849?thread_ts=1700184277.640529&cid=C03FA2M1MR9).

### CODE REVIEW

**Comment by vivbak** [comment]
Hey Kat! This is great, but it's pending the file existing in cpg-common. (Cause I believe thats where that reference path should send it to) Pending this https://centrepopgen.slack.com/archives/C030X7WGFCL/p1700445930576169

**Review by vivbak — APPROVED** [review]

**Review by vivbak — CHANGES_REQUESTED** [review]
Could you take a look at the failing tests?

**Comment by KatalinaBobowik** [comment]
> Could you take a look at the failing tests?

Do you mean the `UnsupportedFileSystemException: No FileSystem for scheme "gs"`. That seems like a GCS connector issue. However, the script finishes successfully and I checked the output in the `test` bucket

**Review by vivbak — APPROVED** [review]
Yay! Tests are passing, once your test run finishes feel free to merge.

**Pull request merged**
